---
title: "RWorksheet_Andica#2.rmd"
author: "John Laurence Andica"
date: "2024-09-23"
output: html_document
---

gg
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Number 1.
```{r}
# [1.] Create a vector using : operator
#      a. Sequence from -5 to 5. Write the R code and its output.
#         Describe its output.

seq1 <- -5:5
seq1
#     The output of the code is numbers from -5 to 5
#      b. x <- 1:7. What will be the value of x?
#         The value of x will be numbers from 1 to 7
#       1 2 3 4 5 6 7

```
Number 2.
```{r}
# [2.] Create a vector using seq() function
#      a. seq(1, 3, by=0.2) specify step size
#         Write the R script and its output. Describe the output.
#     The code generates numbers starting from 1 increment the value by 0.2 until it reaches 3.0 then it will stop incrementing and printing.
seq2 <- seq(1, 3, by = 0.2)
seq2
```
Number 3.
```{r}
# [3.] A factory has a census of its workers. There are 50 workers in total. The following list shows their ages: 34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50,  37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18.
workers <- list(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50,  37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
#      a. Access 3rd element, what is the value?
print(paste(workers[[3]], "is the value of the 3rd element"))
#      b. Access 2nd and 4th element, what are the values?
print(paste(workers[[2]], "is the 2nd element and", workers[[4]], "is the 4th element"))
#      c. Access all but the 4th and 12th element is not included. Write the R script and its output.
exclude <- workers[-c(4, 12)]
exclude
```
Number 4.
```{r}
# [4.] Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the vector, names(x).
x <- c("first" = 3, "second" = 0, "third" = 9)
#      a & b. Print the results. Then access x[c("first", "third")]. COde and its output. Describe the output.
# First it outputs the elements of x.
x
# Then names(x) access and outputs only the names or string in the element.
names(x)
# Lastly x[c("first", "third")] outputs the elements corresponding to first and third.
x[c("first", "third")]
```
Number 5.
```{r}
# [5.] Create a sequence x from -3:2.
x <- c(-3:2)
x
#      a & b. Modify 2nd element and change it to 0. Code and output. Describe the output.
# The code changes the 2nd element from -2 to 0
x[2] <- 0
x
```
Number 6.
```{r}
# [6.] Data was given showing the diesel fuel purchased by Mr. Cruz.
#      a. Create a data frame for month, price per liter (php) and purchase-quantity (liter). Write the R scripts and its output.
mrCruzdata <- data.frame(
  Month = c("Jan", "Feb", "Mar", "Apr", "May", "Jun"),
  Price_Per_Liter = c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00),
  Purchase_Quantity = c(25, 30, 40, 50, 10, 45)
)
mrCruzdata
#      b. What is the average fuel expenditure of Mr. Cruz from Jan to June? Note: Use ‘weighted.mean(liter, purchase)‘. Write the R scripts and its output.
avr_fuel <- weighted.mean(mrCruzdata$Price_Per_Liter, mrCruzdata$Purchase_Quantity)
print(paste("Mr. Cruz avarage fuel expenditure is", avr_fuel))
```
Number 7.
```{r}
# [7.] R has actually lots of built-in datasets. For example, the rivers data “gives the lengths (in miles) of 141 “major” rivers in North America, as compiled by the US Geological Survey”.
#      a. Type “rivers” in your R console. Create a vector data with 7 elements, containing the number of elements (length) in rivers, their sum (sum), mean (mean), median(median), variance(var), standard deviation(sd), minimum (min) and maximum (max).
#This would be the output if "rivers" were typed in the R Console:
rivers
#      b & c. R scripts and outputs. And result.
# The result would be that the data vector will access the rivers data sets and get its length, sum, mean, median, variance, standard deviation, its minimun and maximum.
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
datf <- data.frame(
  DATA = c("Length", "Sum", "Mean", "Median", "Variance", "Std.Dvn.", "Minimum", "Maximum"),
  VALUE = data
)
datf
```
Number 8.
```{r}
# [8.] A table was given with the 25 most powerful celebrities and their annual pay as ranked by the editions of Forbes magazine and as listed on the Forbes.com website.
#      a. Create vectors according to the above table. Write the R scripts and its output.
power_ranking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
celebrity_name <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K. Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Kobe Bryant")
pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
power_ranking
celebrity_name
pay
#      b. Modify the power ranking and pay of J.K. Rowling. Change power ranking to 15 and pay to 90. Write the R scripts and its output.
celebrity_name[19] <- "J.K. Rowling"
power_ranking[19] <- 15
pay[19] <- 90
power_ranking
celebrity_name
pay
#      C. Create an excel file from the table above and save it as csv file(PowerRanking). Import the csv file into the RStudio. What is the R script?
forbes_data <- read.csv("PowerRanking.csv")

#      d. Access the rows 10 to 20 and save it as Ranks.RData. Write the R script and its output.
forbes_data[10:20, ]
ranks <- forbes_data[10:20, ]
save(ranks, file = "Ranks.RData")
#      e. Describe its output.
# The output table containing rows 10 to 20. This includes the celebrities ranked from 10th to 20th position, their names, and their corresponding pay, which is stored in the csv file.
```
Number 9.
```{r}
# [9.] Download the Hotels-Vienna https://tinyurl.com/Hotels-Vienna
#      a. Import the excel file into your RStudio. What is the R script?
library(openxlsx)
vienna <- read.xlsx("hotels-vienna.xlsx")
#      b.   How many dimensions does the dataset have? What is the R script? WHat is its output?
dim(vienna)
#      c. Select columns country, neighbourhood, price, stars, accomodation_type, and ratings. Write the R script.
selcol <- vienna[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
#      d. Save the data as **new.RData to your RStudio. Write the R script.
save(selcol, file = "new.RData")
#      e. Display the first six rows and last six rows of the new.RData. What is the R script?
load("new.RData")
head(selcol)
tail(selcol)
```

Number 10.
```{r}
# [10.] Create a list of ten (10) vegetables you ate during your lifetime. If none, just list down.
#       a. Write the R scripts and its output.
veg <- list("Kangkong", "Papaya", "Sayote", "Okra", "Kalabasa", "Pechay", "Talong", "Ampalaya", "Sitaw", "Malunggay")
veg
#       b. Add 2 additional vegetables after the last vegetables in the list. What is the R script and its output?
veg <- append(veg, list("Labanos", "Patatas"))
veg
#       c. Add 4 additional vegetables after index 5. How many datapoints does your vegetable list have? What is the R script and its output?
veg <- append(veg, list("Tawgi", "Lettuce", "Repolyo", "Pipino"), after = 5)
veg
#       d. Remove the vegetables in index 5, 10, and 15. How many vegetables were left? Write the codes and its output.
veg <- veg[-c(5, 10, 15)]
veg
```
