---
title: "Worksheet_Caneso&Celestra#5a"
author: "Rovel Jan Caneso"
date: "2024-11-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**IMDB URL**
```{r}
library(rvest)
library(httr)
library(polite)

polite::use_manners(save_as = 'polite_scrape.R')

url <- "https://www.imdb.com/chart/toptv/?ref_=nv_tvv_250"

session <- bow(url,
               user_agent = "Educational")
session
```

**Title List**
```{r}
title_list <- scrape(session) %>%
  html_nodes('h3.ipc-title__text') %>%
  html_text

title_list_sub <- as.data.frame(title_list[2:26])
title_list_sub
```

**Split**
```{r}
colnames(title_list_sub) <- "ranks"

split_df <- strsplit(as.character(title_list_sub$ranks),".",fixed = T)
split_df <- data.frame(do.call(rbind,split_df))

colnames(split_df) <- c("ranks", "titles")
split_df
```

**Rating**
```{r}
rating_list <- scrape(session) %>%
  html_nodes('span.ipc-rating-star--rating') %>%
  html_text

rating_list_sub <- as.data.frame(rating_list[1:25])
colnames(rating_list_sub) <- "ratings"
```

**Number of People who voted**
```{r}
people_list <- scrape(session) %>%
  html_nodes('span.ipc-rating-star--voteCount') %>%
  html_text

people_list_sub <- as.data.frame(people_list[1:25])
 

colnames(people_list_sub) <- "people"
```

**Episode and Year it was released**
```{r}
episode_list <- scrape(session) %>%
  html_nodes('span.sc-5bc66c50-6.OOdsw.cli-title-metadata-item:nth-of-type(2)') %>%
  html_text

episode_list_sub <-as.data.frame(episode_list[1:25])

colnames(episode_list_sub) <- "episode"


year_list <- scrape(session) %>%
  html_nodes('span.sc-5bc66c50-6.OOdsw.cli-title-metadata-item:nth-of-type(1)') %>%
  html_text
year_list_sub <-as.data.frame(year_list[1:25])
colnames(year_list_sub) <- "year"
```



**Final List**
```{r}
tv_shows <- cbind(split_df, rating_list_sub, people_list_sub,episode_list_sub, year_list_sub)
write.csv(tv_shows, file = "tv_shows.csv", row.names = F)

```

